RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\http.py", line 1788, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\service\model.py", line 152, in retrying
    result = func()
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\http.py", line 1816, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\http.py", line 2020, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\addons\base\models\ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "c:\users\jaffar_pc\onedrive\desktop\projects\odoo_17\odoo\addons\web\controllers\dataset.py", line 29, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "c:\users\jaffar_pc\onedrive\desktop\projects\odoo_17\odoo\addons\web\controllers\dataset.py", line 20, in _call_kw
    get_public_method(Model, method)  # Don't use the result, call_kw will redo the getattr
  File "C:\Users\Jaffar_Pc\oneDrive\desktop\projects\odoo_17\odoo\odoo\service\model.py", line 36, in get_public_method
    raise AttributeError(f"The method '{model._name}.{name}' does not exist")  # noqa: TRY004
AttributeError: The method 'final.statement.print_final_statement' does not exist

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (http://localhost:8069/web/assets/a2e7ba1/web.assets_web.min.js:2939:163)
        at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/a2e7ba1/web.assets_web.min.js:2943:13)